### PR TITLE
Skip Circle CI if NOCIRCLECI presents on commit message

### PR DESCRIPTION
**Pull request by razonyang**
image

### CODE REVIEW

**Comment by bep** [comment]
Not sure where/how you got the screen shot above, but for me this is what I get:

image

**Comment by bep** [comment]
I'm guessing this is the subtle difference of whether the integration type ... Not sure how to change that and if that has other side effects.

image

**Comment by razonyang** [comment]
> Not sure where/how you got the screen shot above

It was captured from Circle CI dashboard, https://app.circleci.com/pipelines/circleci/qHXqJBvUMYDAjmxWMtFb8/6G1skXJfza7RRuucfmPBW8?branch=release-2

> I'm guessing this is the subtle difference of whether the integration type

Hmm, not sure, I don't remmember there is an option to select while I creating a project on CircleCI.

**Comment by bep** [comment]
>Hmm, not sure, I don't remmember there is an option to select while I creating a project on CircleCI.

I don't think there are, but old setups (like my account and the gohugoio org) was set up many years ago is using the "older" setup.

There's some info about how to move here:

https://circleci.com/docs/github-apps-integration/#Moving-from-github-oauth-app-to-github-app

But I'm very hesitant to even think about doing that. There's a list of "not supported things" and I have spent a great deal of hours getting a release build that's both fast and stable.

**Pull request merged**
